import { type NextRequest, NextResponse } from "next/server"

export async function GET(request: NextRequest) {
  try {
    // Mock restaurant profile data
    const mockProfile = {
      id: "demo-restaurant-123",
      name: "TableSalt Demo Restaurant",
      cuisine: "Modern American",
      description: "A demonstration restaurant showcasing TableSalt AI capabilities",
      location: "San Francisco, CA",
      established: "2024",
    }

    // Mock embeddings (would normally be generated by AI)
    const mockEmbeddings = Array.from({ length: 384 }, () => Math.random() * 2 - 1)

    return NextResponse.json({
      profile: mockProfile,
      embeddings: mockEmbeddings,
      message: "Customer API ready - configure AI services for full functionality",
      status: "success",
    })
  } catch (error) {
    console.error("Error in customers GET:", error)
    return NextResponse.json({ error: "Internal Server Error" }, { status: 500 })
  }
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()

    // Mock customer creation/update
    const mockCustomer = {
      id: `customer-${Date.now()}`,
      ...body,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    }

    return NextResponse.json({
      customer: mockCustomer,
      message: "Customer data processed successfully",
      status: "success",
    })
  } catch (error) {
    console.error("Error in customers POST:", error)
    return NextResponse.json({ error: "Internal Server Error" }, { status: 500 })
  }
}
